name: Build Nuitka Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Compile with Nuitka
      shell: cmd
      run: |
        python -m nuitka ^
          --standalone ^
          --enable-plugin=pyside6 ^
          --assume-yes-for-downloads ^
          --windows-icon-from-ico=resources/images/microphone-black-shape.ico ^
          --windows-console-mode=disable ^
          --output-dir=build ^
          --windows-company-name="TheLordn415 GitHub" ^
          --windows-product-name="StaticMicrophoneVolume" ^
          --windows-file-version="1.1.0" ^
          --windows-product-version="1.1.0" ^
          --windows-file-description="Static Microphone Volume" ^
          --copyright="Copyright TheLordn415 2025" ^
          main.py

    - name: Create release archive
      run: |
        powershell Compress-Archive -Path build\main.dist\* -DestinationPath build\release.zip

    - name: Upload compiled archive
      uses: actions/upload-artifact@v4
      with:
        name: nuitka-release
        path: build/release.zip
